### ISSUE TITLE
Tag releases and add artifacts.

### ISSUE THREAD

**Issue by Foxboron** [N0K0/aicompo-tg19#1]
Learning how to build and deal with golang shouldn't really be needed to participate. It would be great if releases would be tagged and builds for windows and linux/osx uploaded for participants.

**Comment by N0K0** [comment]
Good point! Will fix 👍

**Comment by N0K0** [comment]
Done, a bit of a mess getting it correct.
Never actually released something on Github before 😁

**Comment by Foxboron** [comment]
Awesome, thanks :) Personally been using `hub` for releases.
